name: quick_note
description: "A new Flutter project."
publish_to: "none"

version: 1.2.0+9

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_staggered_grid_view: ^0.7.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  popup_menu: ^2.0.0
  package_info_plus: ^8.0.0
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1
  google_mobile_ads: ^5.1.0
  cached_network_image: ^3.4.0
  html: ^0.15.4
  http: ^1.2.2
  image: ^4.2.0
  url_launcher: ^6.3.0
  reorderable_grid: ^1.0.10
  flutter_svg: ^2.0.10+1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  msix: ^3.16.8

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/quick_note.png
    - assets/logo/quick_note_rectangle.png
    - assets/svg/quick_note.svg
    - assets/svg/quickNote_box.svg

msix_config:
  display_name: QuickNotePad
  publisher_display_name: makjac
  publisher: CN=PLACEHOLDER_PUBLISHER
  identity_name: PLACEHOLDER_IDENTITY_NAME
  msix_version: 1.1.0.0
  logo_path: .\installers\windows\msix\quick_note.png
