// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWnVzvF16mVo3xDj2NvMQgIdSaRSchL4',
    appId: '1:1018705414627:web:153a7dcda3755d9bac78d6',
    messagingSenderId: '1018705414627',
    projectId: 'quicknote-c2a4d',
    authDomain: 'quicknote-c2a4d.firebaseapp.com',
    storageBucket: 'quicknote-c2a4d.appspot.com',
    measurementId: 'G-1CWBQDHP2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJpvrWhI_GLwUGiepT-8l7jMUTFfkmh8',
    appId: '1:1018705414627:android:27a2983ef4e42f6fac78d6',
    messagingSenderId: '1018705414627',
    projectId: 'quicknote-c2a4d',
    storageBucket: 'quicknote-c2a4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZ9Al3vxFd7KF81ju5FGQE9BzjeEQ08c',
    appId: '1:1018705414627:ios:f9947d6a51c31ea6ac78d6',
    messagingSenderId: '1018705414627',
    projectId: 'quicknote-c2a4d',
    storageBucket: 'quicknote-c2a4d.appspot.com',
    iosBundleId: 'com.example.quickNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZ9Al3vxFd7KF81ju5FGQE9BzjeEQ08c',
    appId: '1:1018705414627:ios:f9947d6a51c31ea6ac78d6',
    messagingSenderId: '1018705414627',
    projectId: 'quicknote-c2a4d',
    storageBucket: 'quicknote-c2a4d.appspot.com',
    iosBundleId: 'com.example.quickNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOWnVzvF16mVo3xDj2NvMQgIdSaRSchL4',
    appId: '1:1018705414627:web:be4b90521ef93d85ac78d6',
    messagingSenderId: '1018705414627',
    projectId: 'quicknote-c2a4d',
    authDomain: 'quicknote-c2a4d.firebaseapp.com',
    storageBucket: 'quicknote-c2a4d.appspot.com',
    measurementId: 'G-PZ1LDV6VR6',
  );
}
